baseURL = 'https://diet.fitnessvibe.in/'
languageCode = 'en-us'
paginate = 6
theme= "coHub"
title = 'Niharika Diet Clinit & Yoga Studio'
 
[Menu]
  # Main Menu
  [[menu.Main]]
  name = "Exibhition"
  url= "#gallery"
  weight = 1
  [[menu.Main]]
  name = "Feature"
  url= "#service"
  weight = 1
  [[menu.Main]]
  name = "About"
  url= "/about/"
  weight = 3
  [[menu.Main]]
  name = "Blog"
  url= "#blog"
  weight = 4
  [[menu.Main]]
  name = "Pricing"
  url= "#pricing"
  weight = 5
  [[menu.Main]]
  name = "FAQ"
  url= "#faq"
  weight = 6
  [[menu.Main]]
  name = "Contact"
  url= "/contact/"
  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} <a href=\"https://diet.fitnessvibe.in/\" target=\"_blank\">Niharika's Diet Clinit & Yoga Studio</a>"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  googleAnalytics = "G-SZGQ0JLW8Q"
  logo = "images/logo.png"
  footerlogo = "images/logo.png"
  footerDescription = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit quia ab, natus fugiat voluptas saepe ipsum animi officiis in molestiae?"

  [params.address]
  address = "Unit 103/2, World One High Street Sector 115 Kharar - Landran Rd, Greater, Sahibzada Ajit Singh Nagar, Punjab 140307, India"
  email = "fitnessvibe25@gmail.com"
  openingDesc = "Connect with us on Whatsapp or walk in to our clinic for consultations."
  openingHours = "We are open from 7am — 7pm week days."
  phone = "+(91) 830 577 9442"

  [params.map]
  gmaplink = "Go to contact adress html file and update ifram link directly"
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "45.4502528"
  longitude = "-122.783407"
  pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/"
  weight = 1
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/"
  weight = 2
  
  
