# This is a basic workflow to help you get started with Actions

name: ManualDeploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
           extended: true
           
      - name: Hugo Build
        run: hugo --baseURL https://diet.fitnessvibe.in/
           
      - name: GitHub Pages Deploy
        uses: reuixiy/hugo-deploy@v1
        env:
          DEPLOY_BRANCH: gh-pages
          DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
